Project entity
GoteoFoundation/v4 pull request #7
Opened 2024-04-15 12:21 UTC by davidbeig

Add all the necessary fields for the Project entity.

Comming from the Project model of V3 we have this fields in the Project table

```
id
name
subtitle
lang
currency
currency_rate
status
translate
progress
owner
node
amount
mincost
maxcost
days
num_investors
popularity
num_messengers
num_posts
created
updated
published
success
closed
passed
contract_name
contract_nif
phone
contract_email
address
zipcode
location
country
image
description
motivation
video
video_usubs
about
goal
related
spread
reward
category
keywords
media
media_usubs
currently
project_location
scope
resource
comment
contract_entity
contract_birthdate
entity_office
entity_name
entity_cif
post_address
secondary_address
post_zipcode
post_location
post_country
amount_users
amount_call
maxproj
analytics_id
facebook_pixel
social_commitment
social_commitment_description
execution_plan
sustainability_model
execution_plan_url
sustainability_model_url
sign_url
sign_url_action
```

Some of this fields are inside data for the project (i.e id, owner, etc), some are related to the presentation of the project (i.e, subtitle, description, motivation, etc), also we have some fiscal information in the model (all the fields related to contract)

This has to end now.

We also have some tables with information about a project
```
project
project_account
project_bot
project_category
project_conf
project_data
project_image
project_lang
project_location
project_milestone
project_open_tag
```

This tables will have to be reconfigured.

Right now, the new entity will have fewer details inside it, and we will handle better the configuration aspects of a campaign, as well as their fields to aggregate data and show it to the user.

This PR will use the following new fields
```
owner
status
created_at
modified_at
amount
```

To handle the status of the `Project` we will use a `ProjectStatus` enum.

THIS IS A WIP

2024-04-15 13:12 UTC, subiabre requested changes
Great looking draft. I like where this is going, only found a couple of things that didn't seem to be going in alignment with the rest of the work.

2024-04-15 13:12 UTC, subiabre commented on src/Entity/ProjectStatus.php
Can this be a string backed enum instead of using integers? A string backed enum will be exposed in the API responses and API docs as a far more understandable string for the status of the Project. Might be harder to migrate the current data but we can work around that.

Also maybe use the uppercase-first naming convention as exemplified by [the PHP manual on enums](https://www.php.net/manual/en/language.enumerations.basics.php).

2024-04-15 13:12 UTC, subiabre commented on src/Entity/Project.php
> +    private int $amount;
What is the purpose of this `amount` property? If it's of any monetary relevance I suggest using a  [`Money`](https://github.com/GoteoFoundation/v4/blob/main/src/Entity/Money.php) instead of an integer. This class allows for future compatibility with the [brick/money](https://github.com/brick/money) package to perform safer monetary calculations and solve further possible issues due to the usage of int or float types to handle money, such as memory overflow, currency conversion and cash rounding.

2024-04-15 16:05 UTC, davidbeig commented on src/Entity/ProjectStatus.php
Thanks! Was going to talk to you about just that! I don't really like how we have been managing status inside goteo in v3, not only in the Project model/entity, but also in Invests and others, i think that with numbers it takes more mind bandiwth (is that a thing?).

Will follow what you said. Also we can rethink the status

2024-04-17 13:14 UTC, subiabre requested changes

2024-04-17 13:14 UTC, subiabre commented on src/Entity/Project.php
> +    private ?Money $amount;
The `Money` class also has an `amount` property. Accessing the details of this money would be `amount.amount` and `amount.currency`, very weird looking first call to me. Can this property be renamed to something like`$money` (or a name more conveying of its meaning like `goal` if this is for the money the project hopes to raise) instead? Aswell as the setters and getters for it.

2024-04-17 13:14 UTC, subiabre commented on src/Entity/Project.php
> +    #[ORM\Column(type: 'int')]
The `Money` class is an Embeddable ([see Doctrine documentation](https://www.doctrine-project.org/projects/doctrine-orm/en/3.1/tutorials/embeddables.html)), the correct attribute to specify the ORM usage should be:

```php
#[ORM\Embedded(class: Money::class)]
```

Also why is this property not writable by the API? I don't think that I've understood the purpose of this property but if it is the project's goal then shouldn't at least the project owners be able to determine the amount they want to raise?

2024-05-06 10:20 UTC, subiabre approved these changes

2024-05-06 10:35 UTC, merged